"""Generated constants from schema definitions.

This file is automatically generated by Ziptie from your schema definitions.
DO NOT EDIT MANUALLY - changes will be overwritten.

Usage:
    from models import Labels, Properties, RelationshipTypes

    # Use in classifiers
    if data.get(Properties.ip_address):
        return Labels.private_ip_address

    # Use in validators
    if Properties.hostname in data:
        validate_hostname(data[Properties.hostname])
"""


class Labels:
    """Node label constants mapping Python attribute names to actual labels."""
    domain = "Domain"
    email = "Email"
    email_address = "EmailAddress"
    ip_address = "IPAddress"
    private_ip_address = "PrivateIPAddress"
    public_ip_address = "PublicIPAddress"


class Properties:
    """Property name constants mapping Python attribute names to actual property names."""
    address = "address"
    context = "context"
    count = "count"
    created_at = "created_at"
    from_rel = "from_rel"
    modified_at = "modified_at"
    sources = "sources"
    to = "to"


class RelationshipTypes:
    """Relationship type constants mapping Python attribute names to actual relationship types."""
    from_ = "FROM"
    has_ip = "HAS_IP"
    knows = "Knows"
    to = "TO"
