"""SQL metadata for networksdb entities.

This metadata is used by ziptie-parsing for SQL generation.
SQL generation logic is in ziptie-parsing, not in schema packages.

Generated by ziptie-schema.
"""

# Entity metadata dictionary
sql_metadata = {
    # Global canonical format specifications for all entities
    "_canonical_formats": {
        "node": {
            "version": "1.0",
            "extraction_method": {
                "name": "to_dict",
                "parameters": {"separate_dynamic_properties": True}
            },
            "schema": {
                "node_id": {
                    "type": "string",
                    "required": True,
                    "description": "Deterministic SHA256+Base85 identifier"
                },
                "schema_version": {
                    "type": "string",
                    "required": False,
                    "condition": "present if entity's schema has version"
                },
                "primary_label": {
                    "type": "string",
                    "required": True,
                    "description": "Primary label of the node"
                },
                "labels": {
                    "type": "list",
                    "items_type": "string",
                    "required": True,
                    "merge_strategy": "union",
                    "description": "All labels including primary and additional labels"
                },
                "identifying_properties": {
                    "type": "dict",
                    "required": True,
                    "description": "Properties used for ID generation"
                },
                "properties": {
                    "type": "dict",
                    "required": True,
                    "description": "All non-identifying properties"
                },
                "dynamic_properties": {
                    "type": "dict",
                    "required": False,
                    "condition": "present when separate_dynamic_properties=True and entity has dynamic properties"
                }
            }
        },
        "relationship": {
            "version": "1.0",
            "extraction_method": {
                "name": "to_dict",
                "parameters": {"separate_dynamic_properties": True}
            },
            "schema": {
                "rel_id": {
                    "type": "string",
                    "required": True,
                    "description": "Deterministic SHA256+Base85 identifier"
                },
                "schema_version": {
                    "type": "string",
                    "required": False,
                    "condition": "present if entity's schema has version"
                },
                "rel_type": {
                    "type": "string",
                    "required": True,
                    "description": "Relationship type"
                },
                "start_node": {
                    "type": "dict",
                    "required": True,
                    "description": "Source node reference",
                    "properties": {
                        "primary_label": {
                            "type": "string",
                            "required": True
                        },
                        "node_id": {
                            "type": "string",
                            "required": True
                        }
                    }
                },
                "end_node": {
                    "type": "dict",
                    "required": True,
                    "description": "Target node reference",
                    "properties": {
                        "primary_label": {
                            "type": "string",
                            "required": True
                        },
                        "node_id": {
                            "type": "string",
                            "required": True
                        }
                    }
                },
                "identifying_properties": {
                    "type": "dict",
                    "required": True,
                    "description": "Properties used for ID generation"
                },
                "properties": {
                    "type": "dict",
                    "required": True,
                    "description": "All non-identifying properties"
                },
                "dynamic_properties": {
                    "type": "dict",
                    "required": False,
                    "condition": "present when separate_dynamic_properties=True and entity has dynamic properties"
                }
            }
        }
    },
    "PrivateIPAddress": {
        "is_relationship": False,
        "class_name": "PrivateIPAddress",
        "primary_label": "PrivateIPAddress",
        "schema_version": "0.1",
        "has_dynamic_properties": True,
        "properties": {
            # Canonical fields (present in all nodes)
            "node_id": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Deterministic SHA256+Base85 identifier",
            },
            "schema_version": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Schema version for this entity",
            },
            "primary_label": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Primary label of the node",
            },
            "labels": {
                "type": "list",
                "items_type": "string",
                "required": True,
                "merge_strategy": "union",
                "source": "canonical",
                "description": "All labels including primary and additional labels",
            },
            "identifying_properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "Properties used for ID generation",
            },
            "properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "All non-identifying properties",
            },
            "dynamic_properties": {
                "type": "dict",
                "required": False,
                "source": "canonical",
                "description": "Dynamic properties not defined in schema",
            },
            # Schema-specific fields
            "created_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "min",
                "source": "schema",
            },
            "modified_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "max",
                "source": "schema",
            },
            "count": {
                "type": "int",
                "identifying": False,
                "merge_strategy": "sum",
                "source": "schema",
            },
            "sources": {
                "type": "list",
                "identifying": False,
                "merge_strategy": "union",
                "source": "schema",
            },
            "address": {
                "type": "string",
                "identifying": True,
                "merge_strategy": "error_if_different",
                "source": "schema",
            },
            "context": {
                "type": "string",
                "identifying": True,
                "merge_strategy": "error_if_different",
                "source": "schema",
            },
        },
    },
    "PublicIPAddress": {
        "is_relationship": False,
        "class_name": "PublicIPAddress",
        "primary_label": "PublicIPAddress",
        "schema_version": "0.1",
        "has_dynamic_properties": True,
        "properties": {
            # Canonical fields (present in all nodes)
            "node_id": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Deterministic SHA256+Base85 identifier",
            },
            "schema_version": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Schema version for this entity",
            },
            "primary_label": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Primary label of the node",
            },
            "labels": {
                "type": "list",
                "items_type": "string",
                "required": True,
                "merge_strategy": "union",
                "source": "canonical",
                "description": "All labels including primary and additional labels",
            },
            "identifying_properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "Properties used for ID generation",
            },
            "properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "All non-identifying properties",
            },
            "dynamic_properties": {
                "type": "dict",
                "required": False,
                "source": "canonical",
                "description": "Dynamic properties not defined in schema",
            },
            # Schema-specific fields
            "created_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "min",
                "source": "schema",
            },
            "modified_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "max",
                "source": "schema",
            },
            "count": {
                "type": "int",
                "identifying": False,
                "merge_strategy": "sum",
                "source": "schema",
            },
            "sources": {
                "type": "list",
                "identifying": False,
                "merge_strategy": "union",
                "source": "schema",
            },
            "address": {
                "type": "string",
                "identifying": True,
                "merge_strategy": "error_if_different",
                "source": "schema",
            },
        },
    },
    "Domain": {
        "is_relationship": False,
        "class_name": "Domain",
        "primary_label": "Domain",
        "schema_version": "0.1",
        "has_dynamic_properties": False,
        "properties": {
            # Canonical fields (present in all nodes)
            "node_id": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Deterministic SHA256+Base85 identifier",
            },
            "schema_version": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Schema version for this entity",
            },
            "primary_label": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Primary label of the node",
            },
            "labels": {
                "type": "list",
                "items_type": "string",
                "required": True,
                "merge_strategy": "union",
                "source": "canonical",
                "description": "All labels including primary and additional labels",
            },
            "identifying_properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "Properties used for ID generation",
            },
            "properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "All non-identifying properties",
            },
            # Schema-specific fields
            "created_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "min",
                "source": "schema",
            },
            "modified_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "max",
                "source": "schema",
            },
            "count": {
                "type": "int",
                "identifying": False,
                "merge_strategy": "sum",
                "source": "schema",
            },
            "sources": {
                "type": "list",
                "identifying": False,
                "merge_strategy": "union",
                "source": "schema",
            },
            "address": {
                "type": "string",
                "identifying": True,
                "merge_strategy": "error_if_different",
                "source": "schema",
            },
        },
    },
    "EmailAddress": {
        "is_relationship": False,
        "class_name": "EmailAddress",
        "primary_label": "EmailAddress",
        "schema_version": "0.1",
        "has_dynamic_properties": False,
        "properties": {
            # Canonical fields (present in all nodes)
            "node_id": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Deterministic SHA256+Base85 identifier",
            },
            "schema_version": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Schema version for this entity",
            },
            "primary_label": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Primary label of the node",
            },
            "labels": {
                "type": "list",
                "items_type": "string",
                "required": True,
                "merge_strategy": "union",
                "source": "canonical",
                "description": "All labels including primary and additional labels",
            },
            "identifying_properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "Properties used for ID generation",
            },
            "properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "All non-identifying properties",
            },
            # Schema-specific fields
            "created_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "min",
                "source": "schema",
            },
            "modified_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "max",
                "source": "schema",
            },
            "count": {
                "type": "int",
                "identifying": False,
                "merge_strategy": "sum",
                "source": "schema",
            },
            "sources": {
                "type": "list",
                "identifying": False,
                "merge_strategy": "union",
                "source": "schema",
            },
            "address": {
                "type": "string",
                "identifying": True,
                "merge_strategy": "error_if_different",
                "source": "schema",
            },
        },
    },
    "Email": {
        "is_relationship": False,
        "class_name": "Email",
        "primary_label": "Email",
        "schema_version": "0.1",
        "has_dynamic_properties": False,
        "properties": {
            # Canonical fields (present in all nodes)
            "node_id": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Deterministic SHA256+Base85 identifier",
            },
            "schema_version": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Schema version for this entity",
            },
            "primary_label": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Primary label of the node",
            },
            "labels": {
                "type": "list",
                "items_type": "string",
                "required": True,
                "merge_strategy": "union",
                "source": "canonical",
                "description": "All labels including primary and additional labels",
            },
            "identifying_properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "Properties used for ID generation",
            },
            "properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "All non-identifying properties",
            },
            # Schema-specific fields
            "created_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "min",
                "source": "schema",
            },
            "modified_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "max",
                "source": "schema",
            },
            "count": {
                "type": "int",
                "identifying": False,
                "merge_strategy": "sum",
                "source": "schema",
            },
            "sources": {
                "type": "list",
                "identifying": False,
                "merge_strategy": "union",
                "source": "schema",
            },
            "from_rel": {
                "type": "node",
                "identifying": True,
                "merge_strategy": "error_if_different",
                "source": "schema",
            },
            "to": {
                "type": "node_list",
                "identifying": True,
                "merge_strategy": "error_if_different",
                "source": "schema",
            },
        },
    },
    "HAS_IP": {
        "is_relationship": True,
        "class_name": "HasIP",
        "rel_type": "HAS_IP",
        "schema_version": "0.1",
        "has_dynamic_properties": False,
        "properties": {
            # Canonical fields (present in all relationships)
            "rel_id": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Deterministic SHA256+Base85 identifier",
            },
            "schema_version": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Schema version for this entity",
            },
            "rel_type": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Relationship type",
            },
            "start_node": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "Source node reference",
                "properties": {
                    "primary_label": {
                        "type": "string",
                        "required": True,
                    },
                    "node_id": {
                        "type": "string",
                        "required": True,
                    },
                },
            },
            "end_node": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "Target node reference",
                "properties": {
                    "primary_label": {
                        "type": "string",
                        "required": True,
                    },
                    "node_id": {
                        "type": "string",
                        "required": True,
                    },
                },
            },
            "identifying_properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "Properties used for ID generation",
            },
            "properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "All non-identifying properties",
            },
            # Schema-specific fields
            "created_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "min",
                "source": "schema",
            },
            "modified_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "max",
                "source": "schema",
            },
            "count": {
                "type": "int",
                "identifying": False,
                "merge_strategy": "sum",
                "source": "schema",
            },
            "sources": {
                "type": "list",
                "identifying": False,
                "merge_strategy": "union",
                "source": "schema",
            },
        },
    },
    "FROM": {
        "is_relationship": True,
        "class_name": "FromRelationship",
        "rel_type": "FROM",
        "schema_version": "0.1",
        "has_dynamic_properties": False,
        "properties": {
            # Canonical fields (present in all relationships)
            "rel_id": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Deterministic SHA256+Base85 identifier",
            },
            "schema_version": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Schema version for this entity",
            },
            "rel_type": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Relationship type",
            },
            "start_node": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "Source node reference",
                "properties": {
                    "primary_label": {
                        "type": "string",
                        "required": True,
                    },
                    "node_id": {
                        "type": "string",
                        "required": True,
                    },
                },
            },
            "end_node": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "Target node reference",
                "properties": {
                    "primary_label": {
                        "type": "string",
                        "required": True,
                    },
                    "node_id": {
                        "type": "string",
                        "required": True,
                    },
                },
            },
            "identifying_properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "Properties used for ID generation",
            },
            "properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "All non-identifying properties",
            },
            # Schema-specific fields
            "created_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "min",
                "source": "schema",
            },
            "modified_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "max",
                "source": "schema",
            },
            "count": {
                "type": "int",
                "identifying": False,
                "merge_strategy": "sum",
                "source": "schema",
            },
            "sources": {
                "type": "list",
                "identifying": False,
                "merge_strategy": "union",
                "source": "schema",
            },
        },
    },
    "TO": {
        "is_relationship": True,
        "class_name": "To",
        "rel_type": "TO",
        "schema_version": "0.1",
        "has_dynamic_properties": False,
        "properties": {
            # Canonical fields (present in all relationships)
            "rel_id": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Deterministic SHA256+Base85 identifier",
            },
            "schema_version": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Schema version for this entity",
            },
            "rel_type": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Relationship type",
            },
            "start_node": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "Source node reference",
                "properties": {
                    "primary_label": {
                        "type": "string",
                        "required": True,
                    },
                    "node_id": {
                        "type": "string",
                        "required": True,
                    },
                },
            },
            "end_node": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "Target node reference",
                "properties": {
                    "primary_label": {
                        "type": "string",
                        "required": True,
                    },
                    "node_id": {
                        "type": "string",
                        "required": True,
                    },
                },
            },
            "identifying_properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "Properties used for ID generation",
            },
            "properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "All non-identifying properties",
            },
            # Schema-specific fields
            "created_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "min",
                "source": "schema",
            },
            "modified_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "max",
                "source": "schema",
            },
            "count": {
                "type": "int",
                "identifying": False,
                "merge_strategy": "sum",
                "source": "schema",
            },
            "sources": {
                "type": "list",
                "identifying": False,
                "merge_strategy": "union",
                "source": "schema",
            },
        },
    },
    "Knows": {
        "is_relationship": True,
        "class_name": "Knows",
        "rel_type": "Knows",
        "schema_version": "0.1",
        "has_dynamic_properties": False,
        "properties": {
            # Canonical fields (present in all relationships)
            "rel_id": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Deterministic SHA256+Base85 identifier",
            },
            "schema_version": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Schema version for this entity",
            },
            "rel_type": {
                "type": "string",
                "required": True,
                "source": "canonical",
                "description": "Relationship type",
            },
            "start_node": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "Source node reference",
                "properties": {
                    "primary_label": {
                        "type": "string",
                        "required": True,
                    },
                    "node_id": {
                        "type": "string",
                        "required": True,
                    },
                },
            },
            "end_node": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "Target node reference",
                "properties": {
                    "primary_label": {
                        "type": "string",
                        "required": True,
                    },
                    "node_id": {
                        "type": "string",
                        "required": True,
                    },
                },
            },
            "identifying_properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "Properties used for ID generation",
            },
            "properties": {
                "type": "dict",
                "required": True,
                "source": "canonical",
                "description": "All non-identifying properties",
            },
            # Schema-specific fields
            "created_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "min",
                "source": "schema",
            },
            "modified_at": {
                "type": "iso8601_timestamp",
                "identifying": False,
                "merge_strategy": "max",
                "source": "schema",
            },
            "count": {
                "type": "int",
                "identifying": False,
                "merge_strategy": "sum",
                "source": "schema",
            },
            "sources": {
                "type": "list",
                "identifying": False,
                "merge_strategy": "union",
                "source": "schema",
            },
        },
    },
}
