"""Generated Neo4j index and constraint definitions."""

NEO4J_INDEXES = {
    "constraints": [        {
            "name": "ipaddress_node_id_key",
            "type": "key",
            "labels": ["IPAddress"],
            "properties": ["node_id"],
            "schema_type": "node",
        },        {
            "name": "privateipaddress_node_id_key",
            "type": "key",
            "labels": ["PrivateIPAddress"],
            "properties": ["node_id"],
            "schema_type": "node",
        },        {
            "name": "publicipaddress_node_id_key",
            "type": "key",
            "labels": ["PublicIPAddress"],
            "properties": ["node_id"],
            "schema_type": "node",
        },        {
            "name": "domain_node_id_key",
            "type": "key",
            "labels": ["Domain"],
            "properties": ["node_id"],
            "schema_type": "node",
        },        {
            "name": "emailaddress_node_id_key",
            "type": "key",
            "labels": ["EmailAddress"],
            "properties": ["node_id"],
            "schema_type": "node",
        },        {
            "name": "email_node_id_key",
            "type": "key",
            "labels": ["Email"],
            "properties": ["node_id"],
            "schema_type": "node",
        },        {
            "name": "has_ip_rel_id_key",
            "type": "key",
            "labels": ["HAS_IP"],
            "properties": ["rel_id"],
            "schema_type": "relationship",
        },        {
            "name": "from_rel_id_key",
            "type": "key",
            "labels": ["FROM"],
            "properties": ["rel_id"],
            "schema_type": "relationship",
        },        {
            "name": "to_rel_id_key",
            "type": "key",
            "labels": ["TO"],
            "properties": ["rel_id"],
            "schema_type": "relationship",
        },        {
            "name": "knows_rel_id_key",
            "type": "key",
            "labels": ["Knows"],
            "properties": ["rel_id"],
            "schema_type": "relationship",
        },        {
            "name": "ipaddress_address_key",
            "type": "key",
            "labels": ["IPAddress"],
            "properties": ["address"],
            "schema_type": "node",
        },        {
            "name": "privateipaddress_address_key",
            "type": "key",
            "labels": ["PrivateIPAddress"],
            "properties": ["address"],
            "schema_type": "node",
        },        {
            "name": "publicipaddress_address_key",
            "type": "key",
            "labels": ["PublicIPAddress"],
            "properties": ["address"],
            "schema_type": "node",
        },    ],
    
    "indexes": [    ]
}